In [1]:
%matplotlib inline

# PyTorch가 무엇인가요?

Python 기반의 과학 연산 패키지로 다음과 같은 두 집단을 대상으로 합니다:

- NumPy를 대체하면서 GPU를 이용한 연산이 필요한 경우
- 최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우

## Tensors

Tensor는 NumPy의 ndarray와 유사하며, GPU를 사용한 연산 가속도 가능합니다.

In [1]:
from __future__ import print_function
import torch

In [6]:
# 초기화되지 않은 5x3 행렬을 생성합니다
x = torch.empty(5, 3)
print(x)
print(x.size())

tensor([[0.0000e+00, 0.0000e+00, 7.7052e+31],
        [7.2148e+22, 2.5226e-18, 2.5930e-09],
        [1.0243e-11, 7.7194e-10, 1.6599e-07],
        [4.0744e-11, 2.5639e-09, 2.9573e-18],
        [6.7333e+22, 1.7591e+22, 1.7184e+25]])
torch.Size([5, 3])


In [3]:
# 무작위로 초기화된 행렬을 생성합니다
x = torch.rand(5, 3)
print(x)
print(x.dtype, x.size())

tensor([[0.3274, 0.0823, 0.0567],
        [0.1534, 0.2125, 0.5739],
        [0.5321, 0.8680, 0.0535],
        [0.3601, 0.5028, 0.6461],
        [0.1050, 0.7100, 0.8586]])


In [8]:
# dtype이 long이고 0으로 초기화된 5x3 행렬을 생성합니다
x = torch.zeros(5, 3, dtype=torch.long)
print(x)
print(x.dtype, x.size())

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
torch.int64 torch.Size([5, 3])


In [9]:
# 직접 데이터를 넣어서 tensor를 생성합니다
x = torch.tensor([5.5, 3])
print(x)
print(x.dtype, x.size())

tensor([5.5000, 3.0000])
torch.float32 torch.Size([2])


또는 기존 tensor를 바탕으로 새로운 tensor를 만듭니다. 이들 메소드(method)는
사용자로부터 새로운 값을 제공받지 않은 한, 입력 tensor의 속성들(예. dtype)을
재사용합니다.



In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* 메소드는 크기를 받습니다
print(x)
print(x.dtype, x.size())

x = torch.randn_like(x, dtype=torch.float)    # dtype을 오버라이드(Override) 합니다!
print(x)                                      # 결과는 동일한 크기를 갖습니다
print(x.dtype, x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
torch.float64 torch.Size([5, 3])
tensor([[-0.5302, -0.7731, -0.7176],
        [-1.7580,  0.5324,  0.8696],
        [ 0.0825,  1.2970, -1.5762],
        [ 0.5302,  0.9490,  0.6758],
        [ 1.3822, -1.9952, -1.2300]])
torch.float32 torch.Size([5, 3])


행렬의 크기를 구합니다:



In [14]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` 는 튜플(tuple) 타입으로, 모든 튜플 연산을 지원합니다.</p></div>

연산(Operations)
^^^^^^^^^^^^^^^^
연산을 위한 여러가지 문법을 제공합니다. 다음 예제들을 통해 덧셈 연산을 살펴보겠습니다.

덧셈: 문법1



In [ ]:
y = torch.rand(5, 3)
print(x + y)

덧셈: 문법2



In [ ]:
print(torch.add(x, y))

덧셈: 결과 tensor를 인자로 제공



In [ ]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

덧셈: 바꿔치기(in-place) 방식



In [ ]:
# y에 x 더하기
y.add_(x)
print(y)

<div class="alert alert-info"><h4>Note</h4><p>바꿔치기(in-place) 방식으로 tensor의 값을 변경하는 연산 뒤에는 ``_``가 붙습니다.
    예: ``x.copy_(y)``, ``x.t_()`` 는 ``x`` 를 변경합니다.</p></div>

NumPy스러운 인덱싱 표기 방법을 사용하실 수도 있습니다!



In [ ]:
print(x[:, 1])

크기 변경: tensor의 크기(size)나 모양(shape)을 변경하고 싶다면 ``torch.view`` 를 사용합니다:



In [ ]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # -1은 다른 차원에서 유추합니다.
print(x.size(), y.size(), z.size())

만약 tensor에 하나의 값만 존재한다면, ``.item()`` 을 사용하면 숫자 값을 얻을 수 있습니다.



In [ ]:
x = torch.randn(1)
print(x)
print(x.item())

**더 읽을거리:**


  전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산,
  선형 대수, 난수(random number) 등, 100가지 이상의 Tensor 연산은
  `여기 <http://pytorch.org/docs/torch>`_ 에서 확인하실 수 있습니다.

NumPy 변환(Bridge)
-------------------

Torch Tensor를 NumPy 배열(array)로 변환하거나, 그 반대로 하는 것은 매우 쉽습니다.

(Torch Tensor가 CPU 상에 있다면) Torch Tensor와 NumPy 배열은 메모리 공간을
공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다.

Torch Tensor를 NumPy 배열로 변환하기
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [ ]:
a = torch.ones(5)
print(a)

In [ ]:
b = a.numpy()
print(b)

NumPy 배열의 값이 어떻게 변하는지 확인해보세요.



In [ ]:
a.add_(1)
print(a)
print(b)

NumPy 배열을 Torch Tensor로 변환하기
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
np (NumPy) 배열을 변경하면 Torch Tensor의 값도 자동 변경되는 것을 확인해보세요.



In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

CharTensor를 제외한 CPU 상의 모든 Tensor는 NumPy로 변환할 수 있고,
(NumPy에서 Tensor로의) 반대 변환도 가능합니다.

CUDA Tensors
------------

``.to`` 메소드를 사용하여 Tensor를 어떠한 장치로도 옮길 수 있습니다.



In [ ]:
# 이 코드는 CUDA가 사용 가능한 환경에서만 실행합니다.
# ``torch.device`` 를 사용하여 tensor를 GPU 안팎으로 이동해보겠습니다.
if torch.cuda.is_available():
    device = torch.device("cuda")          # CUDA 장치 객체(device object)로
    y = torch.ones_like(x, device=device)  # GPU 상에 직접적으로 tensor를 생성하거나
    x = x.to(device)                       # ``.to("cuda")`` 를 사용하면 됩니다.
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 는 dtype도 함께 변경합니다!